package secure.files;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eimage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dimage = new javax.swing.JLabel();
        etext = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dtext = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        learn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 87));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jLabel2.setText("Secure Files");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Decrypt Image");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 218, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Learn How to use");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 218, 180, 30));

        eimage.setBackground(new java.awt.Color(255, 255, 255));
        eimage.setForeground(new java.awt.Color(255, 255, 255));
        eimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/files/Lock1.jpg"))); // NOI18N
        eimage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eimage.setMinimumSize(new java.awt.Dimension(100, 100));
        eimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eimageMouseClicked(evt);
            }
        });
        jPanel3.add(eimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Encrypt Image");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 218, -1, -1));

        dimage.setBackground(new java.awt.Color(255, 255, 255));
        dimage.setForeground(new java.awt.Color(255, 255, 255));
        dimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/files/unlcok.jpg"))); // NOI18N
        dimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        dimage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dimage.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.add(dimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 110, 110));

        etext.setBackground(new java.awt.Color(255, 255, 255));
        etext.setForeground(new java.awt.Color(255, 255, 255));
        etext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/files/E-key.jpg"))); // NOI18N
        etext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        etext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etext.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.add(etext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 110, 110));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Encrypt Text");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 428, 120, 30));

        dtext.setBackground(new java.awt.Color(255, 255, 255));
        dtext.setForeground(new java.awt.Color(255, 255, 255));
        dtext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/files/E-lock.jpg"))); // NOI18N
        dtext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        dtext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dtext.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.add(dtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 110, 110));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/files/About.jpg"))); // NOI18N
        about.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 110, 110));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Decrypt Text");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 428, 120, 30));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("About Us");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 428, 120, 30));

        learn.setBackground(new java.awt.Color(255, 255, 255));
        learn.setForeground(new java.awt.Color(255, 255, 255));
        learn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/files/learn.jpg"))); // NOI18N
        learn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        learn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        learn.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.add(learn, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 98, 110, 110));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eimageMouseClicked
        // TODO add your handling code here:
        EncryptImage f = new EncryptImage();
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_eimageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel dimage;
    private javax.swing.JLabel dtext;
    private javax.swing.JLabel eimage;
    private javax.swing.JLabel etext;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel learn;
    // End of variables declaration//GEN-END:variables
}
